import { Product } from './types';

export const PRODUCTS: Product[] = [
  // Maharani's Collection (Women)
  {
    id: 'w1',
    name: 'The Rani Chrono',
    category: 'Watches',
    collection: 'Maharani',
    price: 115000,
    description: 'A masterpiece for the modern queen. Featuring deep garnet straps and a mother-of-pearl dial with gold engravings.',
    image: 'https://i.pinimg.com/1200x/ed/95/17/ed95175f4a9b1bb7adf7d310e80371af.jpg',
    colors: ['Ruby Red', 'Emerald Green', 'Pearl White'],
    material: 'Full-grain Italian Suede Leather',
    isFeatured: true,
  },
  {
    id: 'w2',
    name: 'The Sahiba Tote',
    category: 'Bags',
    collection: 'Maharani',
    price: 145000,
    description: 'An expansive travel tote inspired by the private courtyards of the palace. Elegance that holds your world.',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=800',
    colors: ['Gold', 'Burgundy'],
    material: 'Hand-dyed Buffalo Leather',
    isFeatured: true,
  },
  {
    id: 'w3',
    name: 'The Mumtaz Clutch',
    category: 'Bags',
    collection: 'Maharani',
    price: 38000,
    description: 'A clutch that whispers secrets of the Taj. Soft leather adorned with gold-plated accents.',
    image: 'https://i.pinimg.com/1200x/c6/4d/2e/c64d2ea3ecc3e97890806ed1ef62fb2e.jpg',
    colors: ['Emerald', 'Ruby', 'Sapphire'],
    material: 'Supple Nappa Leather',
    isNew: true,
  },
  {
    id: 'w4',
    name: 'The Noor Flats',
    category: 'Shoes',
    collection: 'Maharani',
    price: 42000,
    description: 'Leather juttis reinvented for modern comfort while retaining royal embroidery.',
    image: 'https://i.pinimg.com/736x/dd/00/30/dd0030ff14a95ac671dfdcc8d92aa907.jpg',
    colors: ['Saffron', 'Turquoise'],
    material: 'Nappa Leather with Gold Stitching',
  },
  {
    id: 'w5',
    name: 'The Begum Belt',
    category: 'Belts',
    collection: 'Maharani',
    price: 18500,
    description: 'A waist cincher of unparalleled grace. Crafted from smooth saddle leather with a handcrafted gold filigree buckle.',
    image: 'https://i.pinimg.com/1200x/89/95/0a/89950a9fbefbf6de7d7c49c56d980b4c.jpg',
    colors: ['Royal Tan', 'Jet Black'],
    material: 'Full-grain Saddle Leather',
    isNew: true,
  },
  {
    id: 'w6',
    name: 'The Noor Carryall',
    category: 'Bags',
    collection: 'Maharani',
    price: 92000,
    description: 'A stately carryall for the regal nomad. Hand-crafted from top-grain leather with subtle royal gold-embossed hardware.',
    image: 'https://i.pinimg.com/736x/cc/40/38/cc40382c92902c2d4204e24a29b99e39.jpg',
    colors: ['Saddle Tan', 'Deep Noir'],
    material: 'Premium Calfskin Leather',
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'w7',
    name: 'The Empress Satchel',
    category: 'Bags',
    collection: 'Maharani',
    price: 158000,
    description: 'An architectural marvel in leather. This structured satchel features intricate hand-woven details and a signature royal emblem.',
    image: 'https://i.pinimg.com/736x/ba/cf/a4/bacfa4dade6a43696c05a4ed9cfbe10a.jpg',
    colors: ['Imperial Red', 'Ivory Cream', 'Royal Blue'],
    material: 'Full-grain Box Calf Leather',
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'w8',
    name: 'The Noor Sovereign',
    category: 'Bags',
    collection: 'Maharani',
    price: 112000,
    description: 'A radiant masterpiece of craftsmanship, designed for the modern sovereign. Features hand-stitched leather and gold-tone hardware that reflects imperial grandeur.',
    image: 'https://i.pinimg.com/736x/7e/91/a0/7e91a0c44e772f2d430cba5cb00734ed.jpg',
    colors: ['Ivory', 'Gold', 'Onyx'],
    material: 'Finest Hand-burnished Leather',
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'w9',
    name: 'The Rajkumari Satchel',
    category: 'Belts',
    collection: 'Maharani',
    price: 128000,
    description: 'A satchel that commands attention in every corridor. Deep ebony leather paired with hand-cast gold hardware for the young sovereign.',
    image: 'https://i.pinimg.com/1200x/06/9f/96/069f9615bb15af6eed7b9d6a314fb2d7.jpg',
    colors: ['Ebony Noir', 'Rich Mahogany'],
    material: 'Top-grain Box Calf Leather',
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'w10',
    name: 'The Chandni Satchel',
    category: 'Watches',
    collection: 'Maharani',
    price: 132000,
    description: 'Inspired by the moonlit marble of the palaces. A piece of luminous elegance, handcrafted for those who carry heritage with grace.',
    image: 'https://i.pinimg.com/736x/77/41/c6/7741c6b053dff255cc18d9dc44a41536.jpg',
    colors: ['Desert Sand', 'Vintage Tan'],
    material: 'Hand-dyed Full-grain Cowhide',
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'w11',
    name: 'The Sultana Pumps',
    category: 'Shoes',
    collection: 'Maharani',
    price: 64000,
    description: 'Architectural heels wrapped in the finest calfskin. A silhouette that defines royal stature and contemporary grace.',
    image: 'https://i.pinimg.com/736x/07/b9/cc/07b9cc8a02ab9c6e069b70360d18cf6d.jpg',
    colors: ['Emerald Noir', 'Sandstone'],
    material: 'Hand-burnished Box Calf Leather',
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'w12',
    name: 'The Noorani Juttis',
    category: 'Shoes',
    collection: 'Maharani',
    price: 48000,
    description: 'Exquisite hand-embroidered leather juttis, featuring intricate Zardosi work on the finest Nappa leather. Designed for walks through imperial gardens.',
    image: 'https://i.pinimg.com/736x/d1/7e/78/d17e78d78ebf47a0de8996603eb9a792.jpg',
    colors: ['Palace Gold', 'Ivory'],
    material: 'Zardosi-embroidered Nappa Leather',
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'w13',
    name: 'The Shahi Mules',
    category: 'Shoes',
    collection: 'Maharani',
    price: 52000,
    description: 'A regal step forward. These hand-crafted mules feature delicate gold-thread accents on velvet-finish leather, embodying the ease of royalty.',
    image: 'https://i.pinimg.com/736x/94/6a/de/946ade3e36c5a643ae10a00828f40b88.jpg',
    colors: ['Deep Maroon', 'Midnight Blue'],
    material: 'Velvet-finish Nappa Leather',
    isNew: true,
    isFeatured: true,
  },

  // Maharaja's Collection (Men)
  {
    id: 'm1',
    name: 'The Shahi Chrono',
    category: 'Watches',
    collection: 'Maharaja',
    price: 135000,
    description: 'Commanding presence with a robust leather strap and a sunray finish dial.',
    image: 'https://i.pinimg.com/736x/10/99/2c/10992c15101a98c91c816d380072f753.jpg',
    colors: ['Tobacco', 'Ebony'],
    material: 'Vachetta Leather',
    isFeatured: true,
  },
  {
    id: 'm2',
    name: 'The Rajput Brogues',
    category: 'Shoes',
    collection: 'Maharaja',
    price: 75000,
    description: 'Hand-burnished oxfords that stand the test of time and tradition.',
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&q=80&w=800',
    colors: ['Cognac', 'Dark Chocolate'],
    material: 'Calfskin Leather',
    isNew: true,
  },
  {
    id: 'm3',
    name: 'The Palace Briefcase',
    category: 'Bags',
    collection: 'Maharaja',
    price: 88000,
    description: 'The ultimate professional companion, crafted with structured leather and brass hardware.',
    image: 'https://i.pinimg.com/736x/d5/da/19/d5da19eab6a5f5e7a888267b92d40167.jpg',
    colors: ['British Tan', 'Black'],
    material: 'Vegetable Tanned Leather',
  },
  {
    id: 'm4',
    name: 'The Heritage Belt',
    category: 'Belts',
    collection: 'Maharaja',
    price: 12000,
    description: 'A touch of texture for formal ensembles, finished with a matte gold buckle.',
    image: 'https://i.pinimg.com/736x/03/d7/08/03d708d9c772fa53f7a47211639a9f68.jpg',
    colors: ['Navy', 'Tan'],
    material: 'Suede Leather',
  },
  {
    id: 'm5',
    name: 'The Imperial Voyager',
    category: 'Bags',
    collection: 'Maharaja',
    price: 125000,
    description: 'A grand duffle for the global sovereign. Hand-stitched from robust buffalo leather with antique brass fittings.',
    image: 'https://i.pinimg.com/1200x/72/9d/c8/729dc87c174568fcbfb9b1208a3a3e93.jpg',
    colors: ['Sienna', 'Deep Onyx'],
    material: 'Full-grain Buffalo Leather',
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'm6',
    name: 'The Durbar Monk-Strap',
    category: 'Shoes',
    collection: 'Maharaja',
    price: 72000,
    description: 'A statement of absolute authority. These double monk-strap boots are hand-painted to achieve a unique patina of aged royalty.',
    image: 'https://i.pinimg.com/736x/72/63/b7/7263b7c5f87972db9c8b5fd74553d539.jpg',
    colors: ['Imperial Brown', 'Midnight Tan'],
    material: 'Hand-painted Crust Leather',
    isNew: true,
    isFeatured: true,
  },
];